
// This file is auto-generated by scripts/generate-ma-helper.mjs
// This file is auto-generated by scripts/generate-ma-helper.mjs
// Do not edit manually. Last updated: 2026-01-30T01:46:02.529Z

export interface LegislatorContact {
    name: string;
    email: string;
    phone: string;
    role: 'Senator' | 'Representative';
}

const LEGISLATOR_DATA: Record<string, LegislatorContact> = {
    "Michael Barrett": {
        "name": "Michael Barrett",
        "email": "Mike.Barrett@masenate.gov",
        "phone": "(617) 722-1572",
        "role": "Senator"
    },
    "Michael Brady": {
        "name": "Michael Brady",
        "email": "Michael.Brady@masenate.gov",
        "phone": "(617) 722-1200",
        "role": "Senator"
    },
    "William Brownsberger": {
        "name": "William Brownsberger",
        "email": "William.Brownsberger@masenate.gov",
        "phone": "(617) 722-1280",
        "role": "Senator"
    },
    "Nick Collins": {
        "name": "Nick Collins",
        "email": "Nick.Collins@masenate.gov",
        "phone": "(617) 722-1150",
        "role": "Senator"
    },
    "Joanne Comerford": {
        "name": "Joanne Comerford",
        "email": "Jo.Comerford@masenate.gov",
        "phone": "(617) 722-1532",
        "role": "Senator"
    },
    "Cynthia Creem": {
        "name": "Cynthia Creem",
        "email": "Cynthia.Creem@masenate.gov",
        "phone": "(617) 722-1639",
        "role": "Senator"
    },
    "Brendan Crighton": {
        "name": "Brendan Crighton",
        "email": "brendan.crighton@masenate.gov",
        "phone": "(617) 722-1350",
        "role": "Senator"
    },
    "John Cronin": {
        "name": "John Cronin",
        "email": "John.Cronin@masenate.gov",
        "phone": "(617) 722-1230",
        "role": "Senator"
    },
    "Julian Cyr": {
        "name": "Julian Cyr",
        "email": "julian.cyr@masenate.gov",
        "phone": "(617) 722-1570",
        "role": "Senator"
    },
    "Sal DiDomenico": {
        "name": "Sal DiDomenico",
        "email": "Sal.DiDomenico@masenate.gov",
        "phone": "(617) 722-1650",
        "role": "Senator"
    },
    "Kelly Dooner": {
        "name": "Kelly Dooner",
        "email": "kelly.dooner@masenate.gov",
        "phone": "(617) 722-1551",
        "role": "Senator"
    },
    "William Driscoll": {
        "name": "William Driscoll",
        "email": "william.driscoll@masenate.gov",
        "phone": "(617) 722-1643",
        "role": "Senator"
    },
    "Peter Durant": {
        "name": "Peter Durant",
        "email": "peter.durant@masenate.gov",
        "phone": "(617) 722-1540",
        "role": "Senator"
    },
    "Lydia Edwards": {
        "name": "Lydia Edwards",
        "email": "Lydia.Edwards@masenate.gov",
        "phone": "(617) 722-1634",
        "role": "Senator"
    },
    "James Eldridge": {
        "name": "James Eldridge",
        "email": "James.Eldridge@masenate.gov",
        "phone": "(617) 722-1120",
        "role": "Senator"
    },
    "Ryan Fattman": {
        "name": "Ryan Fattman",
        "email": "Ryan.Fattman@masenate.gov",
        "phone": "(617) 722-1420",
        "role": "Senator"
    },
    "Paul Feeney": {
        "name": "Paul Feeney",
        "email": "paul.feeney@masenate.gov",
        "phone": "(617) 722-1222",
        "role": "Senator"
    },
    "Dylan Fernandes": {
        "name": "Dylan Fernandes",
        "email": "dylan.fernandes@masenate.gov",
        "phone": "(617) 722-1330",
        "role": "Senator"
    },
    "Barry Finegold": {
        "name": "Barry Finegold",
        "email": "Barry.Finegold@masenate.gov",
        "phone": "(617) 722-1612",
        "role": "Senator"
    },
    "Cindy Friedman": {
        "name": "Cindy Friedman",
        "email": "Cindy.Friedman@masenate.gov",
        "phone": "(617) 722-1432",
        "role": "Senator"
    },
    "Adam G&#243;mez": {
        "name": "Adam G&#243;mez",
        "email": "Adam.Gomez@masenate.gov",
        "phone": "(617) 722-1660",
        "role": "Senator"
    },
    "Patricia Jehlen": {
        "name": "Patricia Jehlen",
        "email": "Patricia.Jehlen@masenate.gov",
        "phone": "(617) 722-1578",
        "role": "Senator"
    },
    "John Keenan": {
        "name": "John Keenan",
        "email": "John.Keenan@masenate.gov",
        "phone": "(617) 722-1494",
        "role": "Senator"
    },
    "Robyn Kennedy": {
        "name": "Robyn Kennedy",
        "email": "Robyn.Kennedy@masenate.gov",
        "phone": "(617) 722-1544",
        "role": "Senator"
    },
    "Jason Lewis": {
        "name": "Jason Lewis",
        "email": "Jason.Lewis@masenate.gov",
        "phone": "(617) 722-1206",
        "role": "Senator"
    },
    "Joan Lovely": {
        "name": "Joan Lovely",
        "email": "Joan.Lovely@masenate.gov",
        "phone": "(617) 722-1410",
        "role": "Senator"
    },
    "Paul Mark": {
        "name": "Paul Mark",
        "email": "Paul.Mark@masenate.gov",
        "phone": "(617) 722-1625",
        "role": "Senator"
    },
    "Liz Miranda": {
        "name": "Liz Miranda",
        "email": "Liz.Miranda@masenate.gov",
        "phone": "(617) 722-1673",
        "role": "Senator"
    },
    "Mark Montigny": {
        "name": "Mark Montigny",
        "email": "Mark.Montigny@masenate.gov",
        "phone": "(617) 722-1440",
        "role": "Senator"
    },
    "Michael Moore": {
        "name": "Michael Moore",
        "email": "Michael.Moore@masenate.gov",
        "phone": "(617) 722-1485",
        "role": "Senator"
    },
    "Patrick O&#39;Connor": {
        "name": "Patrick O&#39;Connor",
        "email": "Patrick.OConnor@masenate.gov",
        "phone": "(617) 722-1646",
        "role": "Senator"
    },
    "Jacob Oliveira": {
        "name": "Jacob Oliveira",
        "email": "Jacob.Oliveira@masenate.gov",
        "phone": "(617) 722-1291",
        "role": "Senator"
    },
    "Pavel Payano": {
        "name": "Pavel Payano",
        "email": "Pavel.Payano@masenate.gov",
        "phone": "(617) 722-1604",
        "role": "Senator"
    },
    "Rebecca Rausch": {
        "name": "Rebecca Rausch",
        "email": "Becca.Rausch@masenate.gov",
        "phone": "(617) 722-1555",
        "role": "Senator"
    },
    "Michael Rodrigues": {
        "name": "Michael Rodrigues",
        "email": "Michael.Rodrigues@masenate.gov",
        "phone": "(617) 722-1114",
        "role": "Senator"
    },
    "Michael Rush": {
        "name": "Michael Rush",
        "email": "Mike.Rush@masenate.gov",
        "phone": "(617) 722-1348",
        "role": "Senator"
    },
    "Karen Spilka": {
        "name": "Karen Spilka",
        "email": "Karen.Spilka@masenate.gov",
        "phone": "(617) 722-1500",
        "role": "Senator"
    },
    "Bruce Tarr": {
        "name": "Bruce Tarr",
        "email": "Bruce.Tarr@masenate.gov",
        "phone": "(617) 722-1600",
        "role": "Senator"
    },
    "John Velis": {
        "name": "John Velis",
        "email": "john.velis@masenate.gov",
        "phone": "(617) 722-1415",
        "role": "Senator"
    },
    "James Arciero": {
        "name": "James Arciero",
        "email": "James.Arciero@mahouse.gov",
        "phone": "(617) 722-2400",
        "role": "Representative"
    },
    "James Arena-DeRosa": {
        "name": "James Arena-DeRosa",
        "email": "James.Arena-DeRosa@mahouse.gov",
        "phone": "(617) 722-2810",
        "role": "Representative"
    },
    "Jennifer Balinsky Armini": {
        "name": "Jennifer Balinsky Armini",
        "email": "Jennifer.Armini@mahouse.gov",
        "phone": "(617) 722-2140",
        "role": "Representative"
    },
    "Shirley Arriaga": {
        "name": "Shirley Arriaga",
        "email": "Shirley.Arriaga@mahouse.gov",
        "phone": "(617) 722-2305",
        "role": "Representative"
    },
    "Brian Ashe": {
        "name": "Brian Ashe",
        "email": "Brian.Ashe@mahouse.gov",
        "phone": "(617) 722-2304",
        "role": "Representative"
    },
    "Bruce Ayers": {
        "name": "Bruce Ayers",
        "email": "Bruce.Ayers@mahouse.gov",
        "phone": "(617) 722-2070",
        "role": "Representative"
    },
    "Michelle Badger": {
        "name": "Michelle Badger",
        "email": "Michelle.Badger@mahouse.gov",
        "phone": "(617) 722-2060",
        "role": "Representative"
    },
    "Christine Barber": {
        "name": "Christine Barber",
        "email": "Christine.Barber@mahouse.gov",
        "phone": "(617) 722-2230",
        "role": "Representative"
    },
    "John Barrett": {
        "name": "John Barrett",
        "email": "john.barrett@mahouse.gov",
        "phone": "(617) 722-2012",
        "role": "Representative"
    },
    "Donald Berthiaume": {
        "name": "Donald Berthiaume",
        "email": "Donald.Berthiaume@mahouse.gov",
        "phone": "(617) 722-2488",
        "role": "Representative"
    },
    "David Biele": {
        "name": "David Biele",
        "email": "David.Biele@mahouse.gov",
        "phone": "(617) 722-2220",
        "role": "Representative"
    },
    "Nicholas Boldyga": {
        "name": "Nicholas Boldyga",
        "email": "Nicholas.Boldyga@mahouse.gov",
        "phone": "(413) 274-8084",
        "role": "Representative"
    },
    "Hannah Bowen": {
        "name": "Hannah Bowen",
        "email": "Hannah.Bowen@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Antonio Cabral": {
        "name": "Antonio Cabral",
        "email": "Antonio.Cabral@mahouse.gov",
        "phone": "(617) 722-2017",
        "role": "Representative"
    },
    "Daniel Cahill": {
        "name": "Daniel Cahill",
        "email": "Daniel.Cahill@mahouse.gov",
        "phone": "(617) 722-2020",
        "role": "Representative"
    },
    "Simon Cataldo": {
        "name": "Simon Cataldo",
        "email": "Simon.Cataldo@mahouse.gov",
        "phone": "(617) 722-2396",
        "role": "Representative"
    },
    "Michael Chaisson": {
        "name": "Michael Chaisson",
        "email": "Michael.Chaisson@mahouse.gov",
        "phone": "(617) 722-2090",
        "role": "Representative"
    },
    "Tackey Chan": {
        "name": "Tackey Chan",
        "email": "Tackey.Chan@mahouse.gov",
        "phone": "(617) 722-2370",
        "role": "Representative"
    },
    "Michelle Ciccolo": {
        "name": "Michelle Ciccolo",
        "email": "michelle.ciccolo@mahouse.gov",
        "phone": "(617) 722-2210",
        "role": "Representative"
    },
    "Mike Connolly": {
        "name": "Mike Connolly",
        "email": "Mike.Connolly@mahouse.gov",
        "phone": "(617) 722-2230",
        "role": "Representative"
    },
    "Rob Consalvo": {
        "name": "Rob Consalvo",
        "email": "Rob.Consalvo@mahouse.gov",
        "phone": "(617) 722-2692",
        "role": "Representative"
    },
    "Manny Cruz": {
        "name": "Manny Cruz",
        "email": "Manny.Cruz@mahouse.gov",
        "phone": "(617) 722-2011",
        "role": "Representative"
    },
    "Mark Cusack": {
        "name": "Mark Cusack",
        "email": "Mark.Cusack@mahouse.gov",
        "phone": "(617) 722-2030",
        "role": "Representative"
    },
    "Leigh Davis": {
        "name": "Leigh Davis",
        "email": "Leigh.Davis@mahouse.gov",
        "phone": "(617) 722-2400",
        "role": "Representative"
    },
    "Michael Day": {
        "name": "Michael Day",
        "email": "Michael.Day@mahouse.gov",
        "phone": "(617) 722-2396",
        "role": "Representative"
    },
    "Marjorie Decker": {
        "name": "Marjorie Decker",
        "email": "Marjorie.Decker@mahouse.gov",
        "phone": "(617) 722-2130",
        "role": "Representative"
    },
    "David DeCoste": {
        "name": "David DeCoste",
        "email": "David.DeCoste@mahouse.gov",
        "phone": "(617) 722-2489",
        "role": "Representative"
    },
    "Kip Diggs": {
        "name": "Kip Diggs",
        "email": "Kip.Diggs@mahouse.gov",
        "phone": "(617) 722-2380",
        "role": "Representative"
    },
    "Mindy Domb": {
        "name": "Mindy Domb",
        "email": "mindy.domb@mahouse.gov",
        "phone": "(617) 722-2060",
        "role": "Representative"
    },
    "Kate Donaghue": {
        "name": "Kate Donaghue",
        "email": "Kate.Donaghue@mahouse.gov",
        "phone": "(617) 722-2013",
        "role": "Representative"
    },
    "Daniel Donahue": {
        "name": "Daniel Donahue",
        "email": "Daniel.Donahue@mahouse.gov",
        "phone": "(617) 722-2637",
        "role": "Representative"
    },
    "Paul Donato": {
        "name": "Paul Donato",
        "email": "Paul.Donato@mahouse.gov",
        "phone": "(617) 722-2520",
        "role": "Representative"
    },
    "Michelle DuBois": {
        "name": "Michelle DuBois",
        "email": "Michelle.DuBois@MAHouse.gov",
        "phone": "(617) 722-2017",
        "role": "Representative"
    },
    "Patricia Duffy": {
        "name": "Patricia Duffy",
        "email": "Patricia.Duffy@mahouse.gov",
        "phone": "(617) 722-2637",
        "role": "Representative"
    },
    "Rodney Elliott": {
        "name": "Rodney Elliott",
        "email": "Rodney.Elliott@mahouse.gov",
        "phone": "(617) 722-2030",
        "role": "Representative"
    },
    "Tricia Farley-Bouvier": {
        "name": "Tricia Farley-Bouvier",
        "email": "Tricia.Farley-Bouvier@mahouse.gov",
        "phone": "(617) 722-2676",
        "role": "Representative"
    },
    "Kimberly Ferguson": {
        "name": "Kimberly Ferguson",
        "email": "Kimberly.Ferguson@mahouse.gov",
        "phone": "(617) 722-2100",
        "role": "Representative"
    },
    "Lisa Field": {
        "name": "Lisa Field",
        "email": "Lisa.Field@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Michael Finn": {
        "name": "Michael Finn",
        "email": "Michael.Finn@mahouse.gov",
        "phone": "(617) 722-2014",
        "role": "Representative"
    },
    "Carole Fiola": {
        "name": "Carole Fiola",
        "email": "Carole.Fiola@mahouse.gov",
        "phone": "(617) 722-2430",
        "role": "Representative"
    },
    "Christopher Flanagan": {
        "name": "Christopher Flanagan",
        "email": "Christopher.Flanagan@mahouse.gov",
        "phone": "(617) 722-2080",
        "role": "Representative"
    },
    "Brandy Fluker-Reid": {
        "name": "Brandy Fluker-Reid",
        "email": "Brandy.FlukerReid@mahouse.gov",
        "phone": "(617) 722-2396",
        "role": "Representative"
    },
    "Paul Frost": {
        "name": "Paul Frost",
        "email": "Paul.Frost@mahouse.gov",
        "phone": "(617) 722-2100",
        "role": "Representative"
    },
    "Dennis Gallagher": {
        "name": "Dennis Gallagher",
        "email": "Dennis.Gallagher@mahouse.gov",
        "phone": "(617) 722-2014",
        "role": "Representative"
    },
    "William Galvin": {
        "name": "William Galvin",
        "email": "William.Galvin@mahouse.gov",
        "phone": "(617) 722-2692",
        "role": "Representative"
    },
    "Sean Garballey": {
        "name": "Sean Garballey",
        "email": "Sean.Garballey@mahouse.gov",
        "phone": "(617) 722-2090",
        "role": "Representative"
    },
    "Judith Garcia": {
        "name": "Judith Garcia",
        "email": "Judith.Garcia@mahouse.gov",
        "phone": "(617) 722-2011",
        "role": "Representative"
    },
    "Colleen Garry": {
        "name": "Colleen Garry",
        "email": "Colleen.Garry@mahouse.gov",
        "phone": "(617) 722-2380",
        "role": "Representative"
    },
    "John Gaskey": {
        "name": "John Gaskey",
        "email": "John.Gaskey@mahouse.gov",
        "phone": "(617) 722-2060",
        "role": "Representative"
    },
    "Carmine Gentile": {
        "name": "Carmine Gentile",
        "email": "carmine.gentile@mahouse.gov",
        "phone": "(617) 722-2810",
        "role": "Representative"
    },
    "Jessica Giannino": {
        "name": "Jessica Giannino",
        "email": "Jessica.Giannino@mahouse.gov",
        "phone": "(617) 722-2020",
        "role": "Representative"
    },
    "Homar G&#243;mez": {
        "name": "Homar G&#243;mez",
        "email": "Homar.Gomez@mahouse.gov",
        "phone": "(413) 977-2676",
        "role": "Representative"
    },
    "Carlos Gonz&#225;lez": {
        "name": "Carlos Gonz&#225;lez",
        "email": "Carlos.Gonzalez@mahouse.gov",
        "phone": "(617) 722-2199",
        "role": "Representative"
    },
    "Kenneth Gordon": {
        "name": "Kenneth Gordon",
        "email": "Ken.Gordon@mahouse.gov",
        "phone": "(617) 722-2070",
        "role": "Representative"
    },
    "Danielle Gregoire": {
        "name": "Danielle Gregoire",
        "email": "Danielle.Gregoire@mahouse.gov",
        "phone": "(617) 722-2140",
        "role": "Representative"
    },
    "Richard Haggerty": {
        "name": "Richard Haggerty",
        "email": "richard.haggerty@mahouse.gov",
        "phone": "(617) 722-2575",
        "role": "Representative"
    },
    "Ryan Hamilton": {
        "name": "Ryan Hamilton",
        "email": "Ryan.Hamilton@mahouse.gov",
        "phone": "(617) 722-2090",
        "role": "Representative"
    },
    "James Hawkins": {
        "name": "James Hawkins",
        "email": "james.hawkins@mahouse.gov",
        "phone": "(617) 722-2013",
        "role": "Representative"
    },
    "Christopher Hendricks": {
        "name": "Christopher Hendricks",
        "email": "Chris.Hendricks@mahouse.gov",
        "phone": "(617) 722-2080",
        "role": "Representative"
    },
    "Natalie Higgins": {
        "name": "Natalie Higgins",
        "email": "Natalie.Higgins@mahouse.gov",
        "phone": "(617) 722-2014",
        "role": "Representative"
    },
    "Kate Hogan": {
        "name": "Kate Hogan",
        "email": "Kate.Hogan@mahouse.gov",
        "phone": "(617) 722-2600",
        "role": "Representative"
    },
    "Russell Holmes": {
        "name": "Russell Holmes",
        "email": "Russell.Holmes@mahouse.gov",
        "phone": "(617) 722-2220",
        "role": "Representative"
    },
    "Kevin Honan": {
        "name": "Kevin Honan",
        "email": "Kevin.Honan@mahouse.gov",
        "phone": "(617) 722-2470",
        "role": "Representative"
    },
    "Tara Hong": {
        "name": "Tara Hong",
        "email": "Tara.Hong@mahouse.gov",
        "phone": "(617) 722-2080",
        "role": "Representative"
    },
    "Vanna Howard": {
        "name": "Vanna Howard",
        "email": "Vanna.Howard@mahouse.gov",
        "phone": "(617) 722-2060",
        "role": "Representative"
    },
    "Steven Howitt": {
        "name": "Steven Howitt",
        "email": "Steven.Howitt@mahouse.gov",
        "phone": "(617) 722-2305",
        "role": "Representative"
    },
    "Daniel Hunt": {
        "name": "Daniel Hunt",
        "email": "Daniel.Hunt@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Bradley Jones": {
        "name": "Bradley Jones",
        "email": "Bradley.Jones@mahouse.gov",
        "phone": "(617) 722-2100",
        "role": "Representative"
    },
    "Hannah Kane": {
        "name": "Hannah Kane",
        "email": "Hannah.Kane@mahouse.gov",
        "phone": "(617) 722-2810",
        "role": "Representative"
    },
    "Kristin Kassner": {
        "name": "Kristin Kassner",
        "email": "Kristin.Kassner@mahouse.gov",
        "phone": "(617) 722-2220",
        "role": "Representative"
    },
    "Patrick Kearney": {
        "name": "Patrick Kearney",
        "email": "patrick.kearney@mahouse.gov",
        "phone": "(617) 722-2017",
        "role": "Representative"
    },
    "Mary Keefe": {
        "name": "Mary Keefe",
        "email": "Mary.Keefe@mahouse.gov",
        "phone": "(617) 722-2017",
        "role": "Representative"
    },
    "Sally Kerans": {
        "name": "Sally Kerans",
        "email": "Sally.Kerans@mahouse.gov",
        "phone": "(617) 722-2210",
        "role": "Representative"
    },
    "Meghan Kilcoyne": {
        "name": "Meghan Kilcoyne",
        "email": "meghan.kilcoyne@mahouse.gov",
        "phone": "(617) 722-2575",
        "role": "Representative"
    },
    "Michael Kushmerek": {
        "name": "Michael Kushmerek",
        "email": "Michael.Kushmerek@mahouse.gov",
        "phone": "(617) 722-2396",
        "role": "Representative"
    },
    "Kathleen LaNatra": {
        "name": "Kathleen LaNatra",
        "email": "kathleen.lanatra@mahouse.gov",
        "phone": "(617) 722-2370",
        "role": "Representative"
    },
    "John Lawn": {
        "name": "John Lawn",
        "email": "John.Lawn@mahouse.gov",
        "phone": "(617) 722-2430",
        "role": "Representative"
    },
    "David LeBoeuf": {
        "name": "David LeBoeuf",
        "email": "david.leboeuf@mahouse.gov",
        "phone": "(617) 722-2305",
        "role": "Representative"
    },
    "Jack Lewis": {
        "name": "Jack Lewis",
        "email": "Jack.Lewis@mahouse.gov",
        "phone": "(617) 722-2582",
        "role": "Representative"
    },
    "David Linsky": {
        "name": "David Linsky",
        "email": "David.Linsky@mahouse.gov",
        "phone": "(617) 722-2810",
        "role": "Representative"
    },
    "Kate Lipper-Garabedian": {
        "name": "Kate Lipper-Garabedian",
        "email": "kate.lipper-garabedian@mahouse.gov",
        "phone": "(617) 722-2960",
        "role": "Representative"
    },
    "Jay Livingstone": {
        "name": "Jay Livingstone",
        "email": "Jay.Livingstone@mahouse.gov",
        "phone": "(617) 722-2011",
        "role": "Representative"
    },
    "Marc Lombardo": {
        "name": "Marc Lombardo",
        "email": "Marc.Lombardo@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Hadley Luddy": {
        "name": "Hadley Luddy",
        "email": "Hadley.Luddy@mahouse.gov",
        "phone": "(617) 722-2582",
        "role": "Representative"
    },
    "William MacGregor": {
        "name": "William MacGregor",
        "email": "bill.macgregor@mahouse.gov",
        "phone": "(617) 722-2020",
        "role": "Representative"
    },
    "Adrian Madaro": {
        "name": "Adrian Madaro",
        "email": "Adrian.Madaro@mahouse.gov",
        "phone": "(617) 722-2320",
        "role": "Representative"
    },
    "John Mahoney": {
        "name": "John Mahoney",
        "email": "John.Mahoney@mahouse.gov",
        "phone": "(617) 722-2575",
        "role": "Representative"
    },
    "Ronald Mariano": {
        "name": "Ronald Mariano",
        "email": "Ronald.Mariano@mahouse.gov",
        "phone": "(617) 722-2500",
        "role": "Representative"
    },
    "Christopher Markey": {
        "name": "Christopher Markey",
        "email": "Christopher.Markey@mahouse.gov",
        "phone": "(617) 722-2676",
        "role": "Representative"
    },
    "John Marsi": {
        "name": "John Marsi",
        "email": "John.Marsi@mahouse.gov",
        "phone": "(617) 722-2240",
        "role": "Representative"
    },
    "Joseph McGonagle": {
        "name": "Joseph McGonagle",
        "email": "Joseph.McGonagle@mahouse.gov",
        "phone": "(617) 722-2015",
        "role": "Representative"
    },
    "Joseph McKenna": {
        "name": "Joseph McKenna",
        "email": "joseph.mckenna@mahouse.gov",
        "phone": "(617) 722-2810",
        "role": "Representative"
    },
    "Paul McMurtry": {
        "name": "Paul McMurtry",
        "email": "Paul.McMurtry@mahouse.gov",
        "phone": "(617) 722-2013",
        "role": "Representative"
    },
    "Rita Mendes": {
        "name": "Rita Mendes",
        "email": "Rita.Mendes@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Joan Meschino": {
        "name": "Joan Meschino",
        "email": "Joan.Meschino@mahouse.gov",
        "phone": "(617) 722-2092",
        "role": "Representative"
    },
    "Aaron Michlewitz": {
        "name": "Aaron Michlewitz",
        "email": "Aaron.M.Michlewitz@mahouse.gov",
        "phone": "(617) 722-2990",
        "role": "Representative"
    },
    "Thomas Moakley": {
        "name": "Thomas Moakley",
        "email": "Thomas.Moakley@mahouse.gov",
        "phone": "(617) 722-2400",
        "role": "Representative"
    },
    "Samantha Monta&#241;o": {
        "name": "Samantha Monta&#241;o",
        "email": "Samantha.Montano@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Frank Moran": {
        "name": "Frank Moran",
        "email": "Frank.Moran@mahouse.gov",
        "phone": "(617) 722-2180",
        "role": "Representative"
    },
    "John Moran": {
        "name": "John Moran",
        "email": "john.moran@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Michael Moran": {
        "name": "Michael Moran",
        "email": "Michael.Moran@mahouse.gov",
        "phone": "(617) 722-2300",
        "role": "Representative"
    },
    "David Muradian": {
        "name": "David Muradian",
        "email": "David.Muradian@mahouse.gov",
        "phone": "(617) 722-2100",
        "role": "Representative"
    },
    "James Murphy": {
        "name": "James Murphy",
        "email": "James.Murphy@mahouse.gov",
        "phone": "(617) 722-2220",
        "role": "Representative"
    },
    "Brian Murray": {
        "name": "Brian Murray",
        "email": "Brian.Murray@mahouse.gov",
        "phone": "(617) 722-2380",
        "role": "Representative"
    },
    "Tram Nguyen": {
        "name": "Tram Nguyen",
        "email": "tram.nguyen@mahouse.gov",
        "phone": "(617) 722-2370",
        "role": "Representative"
    },
    "Norman Orrall": {
        "name": "Norman Orrall",
        "email": "norman.orrall@mahouse.gov",
        "phone": "(617) 722-2090",
        "role": "Representative"
    },
    "Steven Ouellette": {
        "name": "Steven Ouellette",
        "email": "Steve.Ouellette@mahouse.gov",
        "phone": "(617) 722-2060",
        "role": "Representative"
    },
    "Steven Owens": {
        "name": "Steven Owens",
        "email": "Steven.Owens@mahouse.gov",
        "phone": "(617) 722-2230",
        "role": "Representative"
    },
    "Francisco Paulino": {
        "name": "Francisco Paulino",
        "email": "Francisco.Paulino@mahouse.gov",
        "phone": "(617) 722-2060",
        "role": "Representative"
    },
    "Kelly Pease": {
        "name": "Kelly Pease",
        "email": "Kelly.Pease@mahouse.gov",
        "phone": "(413) 875-8787",
        "role": "Representative"
    },
    "Alice Peisch": {
        "name": "Alice Peisch",
        "email": "Alice.Peisch@mahouse.gov",
        "phone": "(617) 722-2783",
        "role": "Representative"
    },
    "Edward Philips": {
        "name": "Edward Philips",
        "email": "Edward.Philips@mahouse.gov",
        "phone": "(617) 722-2400",
        "role": "Representative"
    },
    "Bridget Plouffe": {
        "name": "Bridget Plouffe",
        "email": "Bridget.Plouffe@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Angelo Puppolo": {
        "name": "Angelo Puppolo",
        "email": "Angelo.Puppolo@mahouse.gov",
        "phone": "(617) 722-2006",
        "role": "Representative"
    },
    "Adrianne Ramos": {
        "name": "Adrianne Ramos",
        "email": "Adrianne.Ramos@mahouse.gov",
        "phone": "(617) 722-2140",
        "role": "Representative"
    },
    "Orlando Ramos": {
        "name": "Orlando Ramos",
        "email": "Orlando.Ramos@mahouse.gov",
        "phone": "(617) 722-2430",
        "role": "Representative"
    },
    "Sean Reid": {
        "name": "Sean Reid",
        "email": "Sean.Reid@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Estela Reyes": {
        "name": "Estela Reyes",
        "email": "Estela.Reyes@mahouse.gov",
        "phone": "(617) 722-2240",
        "role": "Representative"
    },
    "David Robertson": {
        "name": "David Robertson",
        "email": "david.robertson@mahouse.gov",
        "phone": "(617) 722-2210",
        "role": "Representative"
    },
    "David Rogers": {
        "name": "David Rogers",
        "email": "Dave.Rogers@mahouse.gov",
        "phone": "(617) 722-2263",
        "role": "Representative"
    },
    "John Rogers": {
        "name": "John Rogers",
        "email": "John.Rogers@mahouse.gov",
        "phone": "(617) 722-2450",
        "role": "Representative"
    },
    "Jeffrey Roy": {
        "name": "Jeffrey Roy",
        "email": "Jeffrey.Roy@mahouse.gov",
        "phone": "(617) 722-2040",
        "role": "Representative"
    },
    "Daniel Ryan": {
        "name": "Daniel Ryan",
        "email": "Dan.Ryan@mahouse.gov",
        "phone": "(617) 722-2240",
        "role": "Representative"
    },
    "Lindsay Sabadosa": {
        "name": "Lindsay Sabadosa",
        "email": "lindsay.sabadosa@mahouse.gov",
        "phone": "(617) 722-2304",
        "role": "Representative"
    },
    "Amy Sangiolo": {
        "name": "Amy Sangiolo",
        "email": "Amy.Sangiolo@mahouse.gov",
        "phone": "(617) 722-2130",
        "role": "Representative"
    },
    "Aaron Saunders": {
        "name": "Aaron Saunders",
        "email": "Aaron.Saunders@mahouse.gov",
        "phone": "(617) 722-2320",
        "role": "Representative"
    },
    "Adam Scanlon": {
        "name": "Adam Scanlon",
        "email": "Adam.Scanlon@mahouse.gov",
        "phone": "(617) 722-2680",
        "role": "Representative"
    },
    "Margaret Scarsdale": {
        "name": "Margaret Scarsdale",
        "email": "Margaret.Scarsdale@mahouse.gov",
        "phone": "(617) 722-2210",
        "role": "Representative"
    },
    "Greg Schwartz": {
        "name": "Greg Schwartz",
        "email": "Greg.Schwartz@mahouse.gov",
        "phone": "(617) 722-2014",
        "role": "Representative"
    },
    "Danillo Sena": {
        "name": "Danillo Sena",
        "email": "Danillo.Sena@mahouse.gov",
        "phone": "(617) 722-2014",
        "role": "Representative"
    },
    "Dawne Shand": {
        "name": "Dawne Shand",
        "email": "Dawne.Shand@mahouse.gov",
        "phone": "(617) 722-2263",
        "role": "Representative"
    },
    "Alan Silvia": {
        "name": "Alan Silvia",
        "email": "Alan.Silvia@mahouse.gov",
        "phone": "(617) 722-2230",
        "role": "Representative"
    },
    "Todd Smola": {
        "name": "Todd Smola",
        "email": "Todd.Smola@mahouse.gov",
        "phone": "(617) 722-2100",
        "role": "Representative"
    },
    "Michael Soter": {
        "name": "Michael Soter",
        "email": "michael.soter@mahouse.gov",
        "phone": "(617) 722-2488",
        "role": "Representative"
    },
    "Priscila Sousa": {
        "name": "Priscila Sousa",
        "email": "Priscila.Sousa@mahouse.gov",
        "phone": "(617) 722-2396",
        "role": "Representative"
    },
    "Thomas Stanley": {
        "name": "Thomas Stanley",
        "email": "Thomas.Stanley@mahouse.gov",
        "phone": "(617) 722-2810",
        "role": "Representative"
    },
    "Alyson Sullivan-Almeida": {
        "name": "Alyson Sullivan-Almeida",
        "email": "alyson.sullivan@mahouse.gov",
        "phone": "(617) 722-2488",
        "role": "Representative"
    },
    "Kenneth Sweezey": {
        "name": "Kenneth Sweezey",
        "email": "Ken.Sweezey@mahouse.gov",
        "phone": "(617) 722-2305",
        "role": "Representative"
    },
    "Mark Sylvia": {
        "name": "Mark Sylvia",
        "email": "Mark.Sylvia@mahouse.gov",
        "phone": "(617) 722-2400",
        "role": "Representative"
    },
    "Joshua Tarsky": {
        "name": "Joshua Tarsky",
        "email": "Joshua.Tarsky@mahouse.gov",
        "phone": "(617) 722-2582",
        "role": "Representative"
    },
    "Justin Thurber": {
        "name": "Justin Thurber",
        "email": "Justin.Thurber@mahouse.gov",
        "phone": "(617) 722-2460",
        "role": "Representative"
    },
    "Jeffrey Turco": {
        "name": "Jeffrey Turco",
        "email": "Jeffrey.Turco@mahouse.gov",
        "phone": "(617) 722-2230",
        "role": "Representative"
    },
    "Chynah Tyler": {
        "name": "Chynah Tyler",
        "email": "Chynah.Tyler@mahouse.gov",
        "phone": "(617) 722-2060",
        "role": "Representative"
    },
    "Steven Ultrino": {
        "name": "Steven Ultrino",
        "email": "Steven.Ultrino@mahouse.gov",
        "phone": "(617) 722-2877",
        "role": "Representative"
    },
    "Erika Uyterhoeven": {
        "name": "Erika Uyterhoeven",
        "email": "Erika.Uyterhoeven@mahouse.gov",
        "phone": "(508) 319-9510",
        "role": "Representative"
    },
    "Andres Vargas": {
        "name": "Andres Vargas",
        "email": "andy.vargas@mahouse.gov",
        "phone": "(617) 722-2080",
        "role": "Representative"
    },
    "Marcus Vaughn": {
        "name": "Marcus Vaughn",
        "email": "Marcus.Vaughn@mahouse.gov",
        "phone": "(617) 722-2263",
        "role": "Representative"
    },
    "David Vieira": {
        "name": "David Vieira",
        "email": "David.Vieira@mahouse.gov",
        "phone": "(617) 722-2230",
        "role": "Representative"
    },
    "Tommy Vitolo": {
        "name": "Tommy Vitolo",
        "email": "tommy.vitolo@mahouse.gov",
        "phone": "(617) 722-2013",
        "role": "Representative"
    },
    "Thomas Walsh": {
        "name": "Thomas Walsh",
        "email": "Thomas.Walsh@mahouse.gov",
        "phone": "(617) 722-2410",
        "role": "Representative"
    },
    "Richard Wells": {
        "name": "Richard Wells",
        "email": "Richard.Wells@mahouse.gov",
        "phone": "(617) 722-2582",
        "role": "Representative"
    },
    "Susannah Whipps": {
        "name": "Susannah Whipps",
        "email": "Susannah.Whipps@mahouse.gov",
        "phone": "(617) 722-2090",
        "role": "Representative"
    },
    "Bud Williams": {
        "name": "Bud Williams",
        "email": "Bud.Williams@mahouse.gov",
        "phone": "(617) 722-2430",
        "role": "Representative"
    },
    "Donald Wong": {
        "name": "Donald Wong",
        "email": "Donald.Wong@mahouse.gov",
        "phone": "(617) 722-2488",
        "role": "Representative"
    },
    "Christopher Worrell": {
        "name": "Christopher Worrell",
        "email": "Christopher.Worrell@mahouse.gov",
        "phone": "(617) 722-2396",
        "role": "Representative"
    },
    "Steven Xiarhos": {
        "name": "Steven Xiarhos",
        "email": "Steven.Xiarhos@mahouse.gov",
        "phone": "(617) 722-2488",
        "role": "Representative"
    },
    "Jonathan Zlotnik": {
        "name": "Jonathan Zlotnik",
        "email": "Jon.Zlotnik@mahouse.gov",
        "phone": "(617) 722-2582",
        "role": "Representative"
    }
};

export const getMALegislatorContact = (nameInput: string, roleInput: string = 'Representative'): LegislatorContact => {
    // 1. Try Direct Match
    // Clean input name: remove "Rep.", "Sen." etc.
    const cleanName = nameInput.replace(/^(Rep.|Sen.|Senator|Representative)s+/i, '').trim();
    
    // exact match
    if (LEGISLATOR_DATA[cleanName]) {
        return LEGISLATOR_DATA[cleanName];
    }
    
    // 2. Try Fuzzy Match (First Last)
    // If input is "Michael J. Barrett" and key is "Michael Barrett"
    // Or input is "Mike Barrett" and key is "Michael Barrett" (harder)
    
    // Let's try to match Last Name and First Letter at least?
    // This handles "Michael J. Barrett" -> "Michael Barrett"
    const parts = cleanName.split(' ');
    const last = parts[parts.length - 1];
    const first = parts[0];
    
    const candidates = Object.values(LEGISLATOR_DATA).filter(p => {
        const pParts = p.name.split(' ');
        const pLast = pParts[pParts.length - 1];
        const pFirst = pParts[0];
        return pLast.toLowerCase() === last.toLowerCase() && pFirst[0].toLowerCase() === first[0].toLowerCase();
    });
    
    if (candidates.length === 1) {
        return candidates[0];
    }
    
    // 3. Last Resort Fallback (Algorithmic)
    // If truly not found (newly elected?), fallback to the old logic or a generic one.
    // Given we scraped the full list, this should be rare.
    
    const role = roleInput.toLowerCase().includes('senat') ? 'Senator' : 'Representative';
    const domain = role === 'Senator' ? 'masenate.gov' : 'mahouse.gov';
    
    return {
        name: cleanName,
        email: `${first}.${last}@${domain}`,
        phone: '(617) 722-2000', // Default switchboard
        role
    };
};
