"use client";

import { useState } from 'react';
import { useSearchParams, useParams } from 'next/navigation';
import jsPDF from 'jspdf';
import { getStateConfig } from '@/lib/states';
import { generateEmailLink } from '@/lib/mail-providers';
import { getCommitteeContact } from '@/lib/committees';
import { getLegislatorContact } from '@/lib/legislator-contact';

export default function WizardForm() {
    const searchParams = useSearchParams();
    const params = useParams();
    const stateCode = typeof params?.state === 'string' ? params.state : 'nh';
    const config = getStateConfig(stateCode);
    const isNH = config.code === 'NH';
    // const isCommitteeBased = config.submissionMethod === 'committee'; // Used implicit check below

    const [step, setStep] = useState(1);
    const [formData, setFormData] = useState({
        bill: searchParams.get('bill') || '',
        committee: searchParams.get('committee') || '',
        date: searchParams.get('date') || '',
        // Capture transparency data from URL if present
        sponsor_name: searchParams.get('sponsor') || '',
        sponsor_party: searchParams.get('party') || '',
        sponsor_election: searchParams.get('election') || '',
        position: 'support', // support, oppose, neutral
        firstName: '',
        lastName: '',
        city: '',
        testimony: '',
    });

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const generatePDF = () => {
        const doc = new jsPDF();
        const margin = 20;
        let yPos = 20;

        // 1. Official Header
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("Official Legislative Testimony", margin, yPos);
        yPos += 10;

        doc.setLineWidth(0.5);
        doc.line(margin, yPos, 190, yPos);
        yPos += 15;

        // 2. Hearing Details (Grid Layout)
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(`Bill: ${formData.bill}`, margin, yPos);
        doc.text(`Date: ${formData.date}`, 120, yPos);
        yPos += 8;

        doc.text(`Committee: ${formData.committee}`, margin, yPos);

        // Position Badge
        doc.setFillColor(formData.position === 'support' ? 220 : 255, formData.position === 'support' ? 255 : 220, 220); // Light Green or Red tint
        doc.rect(120, yPos - 5, 40, 8, 'F');
        doc.setTextColor(0);
        doc.text(`Position: ${formData.position.toUpperCase()}`, 122, yPos);
        yPos += 15;

        // 3. Author Info
        doc.setFont("helvetica", "normal");
        doc.text(`From: ${formData.firstName} ${formData.lastName}`, margin, yPos);
        doc.text(`Resident of: ${formData.city}, NH`, margin, yPos + 6);
        yPos += 15;

        // 4. Transparency Context (If available)
        if (formData.sponsor_name) {
            doc.setFillColor(245, 245, 245); // Light Gray BG
            doc.rect(margin, yPos, 170, 20, 'F');
            doc.setFontSize(10);
            doc.setTextColor(80);
            doc.text("CONTEXT & TRANSPARENCY:", margin + 5, yPos + 6);

            let transparencyText = `Sponsor: ${formData.sponsor_name} (${formData.sponsor_party})`;
            if (formData.sponsor_election) transparencyText += ` | Next Election: ${formData.sponsor_election}`;

            doc.text(transparencyText, margin + 5, yPos + 14);
            yPos += 30;
        } else {
            yPos += 10;
        }

        // 5. Written Testimony Body
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.text("Written Testimony:", margin, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");

        const splitText = doc.splitTextToSize(formData.testimony, 170);
        doc.text(splitText, margin, yPos);

        // Footer
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by US Civic Action | The People's Voice", margin, pageHeight - 10);

        doc.save(`Testimony_${formData.bill}_${formData.lastName}.pdf`);
    };

    return (
        <div className="bg-white rounded-xl shadow-lg border border-granite-100 overflow-hidden">
            {/* Progress Bar */}
            <div className="bg-granite-50 px-6 py-4 border-b border-granite-100 flex items-center justify-between">
                <span className="text-sm font-bold text-granite-800 uppercase tracking-wider">
                    Step {step} of 3
                </span>
                <div className="flex gap-2">
                    {[1, 2, 3].map((i) => (
                        <div
                            key={i}
                            className={`h-2 w-8 rounded-full ${i <= step ? 'bg-nh-green-500' : 'bg-granite-200'}`}
                        />
                    ))}
                </div>
            </div>

            <div className="p-6 md:p-8">
                {step === 1 && (
                    <div className="space-y-6">
                        <h2 className="text-2xl font-bold text-black">Confirm Details</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-bold text-black mb-1">Bill Number</label>
                                <input
                                    type="text"
                                    name="bill"
                                    value={formData.bill}
                                    onChange={handleInputChange}
                                    className="w-full px-4 py-3 rounded-lg border border-granite-300 bg-white text-black font-medium focus:ring-2 focus:ring-nh-green-500 focus:border-nh-green-500 outline-none transition-all"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-black mb-1">Committee</label>
                                <input
                                    type="text"
                                    name="committee"
                                    value={formData.committee}
                                    onChange={handleInputChange}
                                    className="w-full px-4 py-3 rounded-lg border border-granite-300 bg-white text-black font-medium focus:ring-2 focus:ring-nh-green-500 focus:border-nh-green-500 outline-none transition-all"
                                />
                            </div>
                        </div>

                        <div className="pt-4">
                            <label className="block text-sm font-bold text-black mb-2">My Position</label>
                            <div className="flex flex-col md:flex-row gap-3">
                                {['support', 'oppose', 'neutral'].map((pos) => (
                                    <button
                                        key={pos}
                                        type="button"
                                        onClick={() => setFormData({ ...formData, position: pos })}
                                        className={`flex-1 py-3 px-4 rounded-lg font-bold capitalize transition-all ${formData.position === pos
                                            ? 'bg-nh-green-50 border-2 border-nh-green-500 text-nh-green-900 ring-2 ring-nh-green-500/20 shadow-sm'
                                            : 'bg-white border-2 border-granite-300 text-black hover:bg-gray-50 shadow-sm'
                                            }`}
                                    >
                                        {pos}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <button
                            onClick={() => setStep(2)}
                            className="w-full mt-6 bg-black text-white font-bold py-4 rounded-xl shadow-lg hover:bg-black transition-transform active:scale-[0.98]"
                        >
                            Next: Write Testimony
                        </button>
                    </div>
                )}

                {step === 2 && (
                    <div className="space-y-6">
                        <h2 className="text-2xl font-bold text-black">Your Info & Testimony</h2>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-bold text-black mb-1">First Name</label>
                                <input
                                    type="text"
                                    name="firstName"
                                    value={formData.firstName}
                                    onChange={handleInputChange}
                                    placeholder="Jane"
                                    className="w-full px-4 py-3 rounded-lg border border-granite-300 bg-white text-black placeholder-gray-500 font-medium focus:ring-2 focus:ring-nh-green-500 outline-none"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-black mb-1">Last Name</label>
                                <input
                                    type="text"
                                    name="lastName"
                                    value={formData.lastName}
                                    onChange={handleInputChange}
                                    placeholder="Doe"
                                    className="w-full px-4 py-3 rounded-lg border border-granite-300 bg-white text-black placeholder-gray-500 font-medium focus:ring-2 focus:ring-nh-green-500 outline-none"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-black mb-1">City/Town</label>
                            <input
                                type="text"
                                name="city"
                                value={formData.city}
                                onChange={handleInputChange}
                                placeholder="Concord"
                                className="w-full px-4 py-3 rounded-lg border border-granite-300 bg-white text-granite-900 font-medium focus:ring-2 focus:ring-nh-green-500 outline-none"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-black mb-1">
                                Written Testimony
                                <span className="text-granite-500 font-normal ml-2 text-xs">(Keep it brief and personal)</span>
                            </label>
                            <textarea
                                name="testimony"
                                value={formData.testimony}
                                onChange={handleInputChange}
                                rows={6}
                                className="w-full px-4 py-3 rounded-lg border border-granite-300 bg-white text-black placeholder-gray-500 font-medium focus:ring-2 focus:ring-nh-green-500 outline-none resize-none"
                                placeholder="I am writing to support/oppose this bill because..."
                            />
                        </div>

                        <div className="flex gap-4 pt-4">
                            <button
                                onClick={() => setStep(1)}
                                className="flex-1 py-4 text-gray-700 font-bold hover:text-black"
                            >
                                Back
                            </button>
                            <button
                                onClick={() => setStep(3)}
                                className="flex-[2] bg-black text-white font-bold py-4 rounded-xl shadow-lg hover:bg-black transition-transform active:scale-[0.98]"
                            >
                                Review & Export
                            </button>
                        </div>
                    </div>
                )}

                {step === 3 && (
                    <div className="-m-6 md:-m-8">
                        <div className="divide-y divide-granite-100">
                            {/* Section 1: Records */}
                            <div className="p-6 md:p-8 flex gap-5 items-start">
                                <div className="bg-black text-white font-bold text-xl w-10 h-10 rounded-full flex items-center justify-center shrink-0 shadow-sm">1</div>
                                <div className="flex-1 space-y-3">
                                    <h3 className="text-xl font-bold text-black">Save Your Records</h3>
                                    <p className="text-base text-gray-800 leading-relaxed max-w-2xl">
                                        Always keep a copy of your testimony for your records. You may need to reference it later.
                                    </p>
                                    <button
                                        onClick={generatePDF}
                                        className="mt-2 inline-flex items-center gap-2 bg-white border-2 border-granite-200 text-black font-bold py-3 px-5 rounded-lg hover:bg-gray-50 hover:border-granite-300 transition-all shadow-sm active:scale-95"
                                    >
                                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                                        Download PDF
                                    </button>
                                </div>
                            </div>

                            {/* Section 2: Committee */}
                            <div className="p-6 md:p-8 flex gap-5 items-start bg-white">
                                <div className="bg-black text-white font-bold text-xl w-10 h-10 rounded-full flex items-center justify-center shrink-0 shadow-sm">2</div>
                                <div className="flex-1 space-y-3">
                                    <h3 className="text-xl font-bold text-black">Committee Information</h3>
                                    <p className="text-base text-gray-800 leading-relaxed">
                                        This bill is currently being heard by:
                                    </p>
                                    <div className="bg-granite-50 border border-granite-200 rounded-lg p-4 inline-block">
                                        <span className="block text-xs font-extrabold text-granite-500 uppercase tracking-widest mb-1">Target Committee</span>
                                        <span className="text-lg font-bold text-granite-900 dark:text-granite-900">{formData.committee || 'Committee TBD'}</span>
                                    </div>
                                </div>
                            </div>

                            {/* Section 3: Take Action (Dynamic) */}
                            <div className="p-6 md:p-8 flex gap-5 items-start bg-white">
                                <div className="bg-black text-white font-bold text-xl w-10 h-10 rounded-full flex items-center justify-center shrink-0 shadow-sm">3</div>
                                <div className="flex-1 space-y-3">
                                    <h3 className="text-xl font-bold text-black">Take Action</h3>
                                    <p className="text-base text-gray-800 leading-relaxed max-w-2xl">
                                        {config.step3Instructions || "Submit your testimony using the contact info below."}
                                    </p>

                                    {/* Action Type: Direct Contact (MA style) or Fallback to Sponsor Card if data exists */}
                                    {formData.sponsor_name ? (
                                        <div className="bg-white border-2 border-granite-100 rounded-xl p-5 shadow-sm max-w-md mt-2 hover:border-granite-200 transition-colors">
                                            <div className="flex items-center gap-4 mb-5">
                                                <div className="w-12 h-12 bg-granite-100 dark:bg-granite-100 rounded-full flex items-center justify-center text-2xl">
                                                    👤
                                                </div>
                                                <div>
                                                    <span className="block text-xs font-extrabold text-gray-500 uppercase tracking-widest">Bill Sponsor</span>
                                                    {(() => {
                                                        const contact = getLegislatorContact(stateCode, formData.sponsor_name);
                                                        return contact.id ? (
                                                            <a
                                                                href={`/${stateCode}/person/${contact.id}`}
                                                                target="_blank"
                                                                rel="noopener noreferrer"
                                                                className="block font-bold text-black text-xl leading-tight mt-0.5 hover:text-nh-green-700 hover:underline transition-colors"
                                                            >
                                                                {formData.sponsor_name} 🔗
                                                            </a>
                                                        ) : (
                                                            <span className="block font-bold text-black text-xl leading-tight mt-0.5">
                                                                {formData.sponsor_name}
                                                            </span>
                                                        );
                                                    })()}
                                                </div>
                                            </div>

                                            {/* Logic: If Direct Contact, show Email/Call pills. If PDF Generator, show just Email/Info? 
                                                Actually, even for PDF states, showing sponsor contact is transparent and good. 
                                                We'll enable it for all, as 'transparency' is a core value. 
                                            */}
                                            <div className="grid grid-cols-2 gap-3">
                                                <a
                                                    href={`mailto:${getLegislatorContact(stateCode, formData.sponsor_name).email}?subject=Testimony: ${formData.bill}&body=${encodeURIComponent(formData.testimony)}`}
                                                    className="flex items-center justify-center gap-2 bg-white border-2 border-granite-200 hover:bg-granite-50 text-black font-bold py-3 px-4 rounded-lg transition-all active:scale-95 group"
                                                >
                                                    <span className="group-hover:scale-110 transition-transform text-lg">📧</span> Email
                                                </a>
                                                <a
                                                    href={`tel:${getLegislatorContact(stateCode, formData.sponsor_name).phone}`}
                                                    className="flex items-center justify-center gap-2 bg-white border-2 border-granite-200 hover:bg-granite-50 text-black font-bold py-3 px-4 rounded-lg transition-all active:scale-95 group"
                                                >
                                                    <span className="group-hover:scale-110 transition-transform text-lg">📞</span> Call
                                                </a>
                                            </div>
                                            <div className="mt-4 text-center">
                                                <span className="text-xs text-granite-500 dark:text-granite-400 font-mono select-all bg-granite-50 dark:bg-granite-100 px-2 py-1 rounded">
                                                    {getLegislatorContact(stateCode, formData.sponsor_name).email}
                                                </span>
                                            </div>
                                        </div>
                                    ) : (
                                        <div className="bg-amber-50 dark:bg-amber-900/30 border border-amber-200 dark:border-amber-800 rounded-lg p-5">
                                            <p className="text-sm text-amber-900 dark:text-amber-100 font-bold mb-2">Sponsor Info Unavailable</p>
                                            {config.findLegislatorLink && (
                                                <a
                                                    href={config.findLegislatorLink}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="inline-flex items-center gap-1 text-sm font-bold text-amber-800 dark:text-amber-200 hover:underline hover:text-amber-950 dark:hover:text-amber-100"
                                                >
                                                    Find Your Legislator &rarr;
                                                </a>
                                            )}
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>

                        <div className="text-center pt-8 bg-granite-50 dark:bg-granite-50 border-t border-granite-100 dark:border-granite-200 p-6 md:p-8">
                            <button
                                onClick={() => setStep(2)}
                                className="text-sm text-gray-500 font-bold hover:text-black transition-colors uppercase tracking-wider"
                            >
                                &larr; Back to Edit
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
